version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries: '*'
    target-branch: 'main'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore'
      include: 'scope'
  - package-ecosystem: 'github-actions'
    directory: '/'
    registries: '*'
    target-branch: 'develop'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore'
      include: 'scope'
