name: ci
on: [pull_request]

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  install:
    name: install
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: yarn install
  test:
    name: testing
    needs: install
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
      - run: yarn lint:report
      - run: yarn format
      - run: yarn test:cov
      - name: Upload test-report for analysis
        uses: actions/upload-artifact@v1
        with:
          name: test-reports
          path: reports/
  dependabot:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
